### ISSUE TITLE
where can  i find yolov8 prediction result?

### ISSUE THREAD

**Issue by BinHuangScut** [ouphi/yolov8-with-azureml#6]
Thank you so much for your work. It is extremely useful for me.

I am a newbie to Azure ML, and I have been learning step by step following your tutorial. I have trained a model. Now I want to use it to predict some images.  I want to know how to obtain the image with prediction, which is the image marked with bounding boxes, using the Python SDK or command line. I tried to make predictions using the code below, but I can't find the saved image. Sincerely appreciate your inputs.

```
from azure.ai.ml import command
from azure.ai.ml import Input

job3 = command(
    code="training-code",
    command="""
        python ts.py 
    """,
    environment="azureml:yolov8-environment:1",
    compute="CPU-mini",
    display_name="yolov8-predict",
    experiment_name="yolov8-experiment"
)
```

```
ts.py:

from ultralytics import YOLO

# Load a model
model = YOLO('best.pt')  # pretrained YOLOv8n model

# Run batched inference on a list of images
results = model(['test.png'],save=True,project="xxx", name="xxx")  # return a list of Results objects
```

Here is the output and log:

0: 352x640 2 poles, 1 vegetation_encroachment, 73.5ms
Speed: 5.0ms preprocess, 73.5ms inference, 1.6ms postprocess per image at shape (1, 3, 352, 640)
Results saved to [1m/xxx/xxx[0m

**Comment by ouphi** [comment]
Hi @BinHuangScut, thank you for reaching out. I am happy that you find the tutorial useful.
Due to isolation of AzureML jobs, files written during the jobs are not persisted outside of the job environment. Note that there is an exception to this rule, files saved to the `./outputs` and the `./logs` folder can be retrieved after the job run (you can find more information [here](https://learn.microsoft.com/en-us/azure/machine-learning/how-to-save-write-experiment-files?view=azureml-api-1#where-to-write-files))
You have 2 options to save and retrieve the images:
## Option 1: Specify `project="./outputs"`
Pass a parameter project="./outputs" to save the images to the outputs folder.
`results = model(['test.png'],save=True,project="./outputs", name="xxx")`
Then you will retrieve the images in the `Outputs + Logs` > `outputs` after the job run.
Note that this solution has a limitation: Be mindful of the number and size of files written to this folder, as latency may occur when the contents are uploaded to job history. If latency is a concern, writing files to a datastore is recommended (see option 2).

## Option 2 - Leverage AzureML job outputs to write data to Azure Storage
Save the images to blob storage by using [AzureML output](https://learn.microsoft.com/en-us/python/api/azure-ai-ml/azure.ai.ml.output?view=azure-python).

You would need to do something like this:
```python
from azure.ai.ml import command
from azure.ai.ml import Input
from azure.ai.ml import Output

job3 = command(
    code="training-code",
    command="""
        python ts.py --results_folder ${{outputs.results_folder}}
    """,
    environment="azureml:yolov8-environment:1",
    outputs=dict(results_folder=Output(type="uri_folder", mode="rw_mount")),
    compute="CPU-mini",
    display_name="yolov8-predict",
    experiment_name="yolov8-experiment"
)
```

The output path needs to be passed to your python script ts.py:
```python
import argparse
from ultralytics import YOLO

parser = argparse.ArgumentParser()
parser.add_argument("--results_folder", type=str, help="path to results folder")
args = parser.parse_args()
results_folder = args.results_folder

# Load a model
model = YOLO('best.pt')  # pretrained YOLOv8n model

# Run batched inference on a list of images
results = model(['test.png'], save=True, project=results_folder, name="xxx")  # return a list of Results objects
```python

**Comment by BinHuangScut** [comment]
That perfectly addressed my issue. Really appreciate your work.
